packages:
  - 'base/'
  - 'jsx-stylish/'
  - 'jsx/'
  - 'modern/'
  - 'modules/'
  - 'node/'
  - 'prettier/'
  - 'react/'
  - 'stylish/'
  - 'typescript-strict/'
  - 'typescript-stylish/'
  - 'typescript/'
