module.exports = {
  rules: {
    'arrow-body-style': 'error',
    'arrow-parens': ['error', 'always'],
    'arrow-spacing': 'error',
    'block-spacing': 'error',
    'dot-location': ['error', 'property'],
    'dot-notation': 'error',
    'no-else-return': 'error',
    'no-extra-bind': 'error',
    'no-extra-label': 'error',
    'no-floating-decimal': 'error',
    'no-multi-spaces': 'error',
    'prefer-arrow-callback': 'error',
    'prefer-destructuring': 'error',
    'rest-spread-spacing': 'error',
    'template-curly-spacing': 'error',
    'wrap-iife': ['error', 'any'],
    'yoda': 'error',
    'yield-star-spacing': ['error', 'after'],
  },
}
